server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class_manager?serverTimezone=UTC
    username: root
    password: enHP9FeFKG4E
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security: # <-- 添加这部分
    user:
      name: fixeduser # 自定义用户名，例如 'myuser'
      password: xFqHWFRSyNU9Ywspa9Qb # 自定义密码，请替换为强密码
      roles: USER # 可以设置角色
